### ISSUE TITLE
Platform landing page

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#38]
**__User Story Summary__**
Main entry point to the platform. The landing page will be where the user reads some information about the platform and where he can register and sign in.

**__Stories__**
- [x] As a **user** I should be able to **see the business proposal** so that **I can make a quick impression about the platform**
- [x] As a **user** I should be able to **see a list of features of the platform** so that **I can understand what the platform has to offer**
- [x] As a **user** I should be able to **see a CTA for signing up** so that **I can quickly try out the platform**
- [x] As a **user** I should be able to **see a list of useful links** so that **I can navigate through the most important pages**
- [ ] As a **user** I should be able to **read the terms of usage**
- [ ] As a **user** I should be able to **read the privacy page**

**__Test__**
Landing page completes all the requirements

**__Additional Considerations__**
[Landing UI](https://assets.materialup.com/uploads/796fee2d-432a-4348-b1ac-09fdc68b4905/attachment.png)
