### ISSUE TITLE
DB modeling and diagraming

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#41]
**__Task Description__**
- [x] Model **users** table
- [x] Model **books** table
- [x] Model **categories** table
- [x] Model **authors** table
- [x] Model **reviews** table
- [x] Model **reading_lists** table
- [x] Set relationships between tables

**__Technical Considerations__**

**__Additional Considerations__**
[MoonModeler](https://www.datensen.com/data-modeling/moon-modeler-for-databases.html)

**Comment by sohanur-rahman0** [comment]
[https://app.zenhub.com/files/401346050/c32665c1-0f5e-45ca-b745-9c99961a1bc8/download](https://app.zenhub.com/files/401346050/c32665c1-0f5e-45ca-b745-9c99961a1bc8/download)
initial Schema designs

**Comment by Kerosz** [comment]
@sohanur-rahman0 Looks great! 👍🏻
