### ISSUE TITLE
UX/UI Designs

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#42]
**__Task Description__**
- [x] Pick a good design for the **landing page**
- [x] Pick a good design for the **admin dashboard / CMS**
- [x] Pick a good design for the **main application platform**

**__Technical Considerations__**

**__Additional Considerations__**
[Uplabs](https://www.uplabs.com/)
[UI8](https://ui8.net/)
[Admin UI](https://minimals.cc/dashboard/app)
[Landing UI](https://assets.materialup.com/uploads/796fee2d-432a-4348-b1ac-09fdc68b4905/attachment.png)
