### ISSUE TITLE
End-user survey

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#43]
**__Task Description__**
- [x] Setup a survey for end-users to include questions about core features
- [x] Ask information about their age category, demographics, and other useful metrics
- [x] Have a description about the app mission in the survey
- [x] Include questions about how important some of the features from our backlog are for them
- [x] Include fields about what other features they will like to see 

**__Technical Considerations__**

**__Additional Considerations__**

**Comment by Kerosz** [comment]
User survey created at: [https://s.surveyplanet.com/q5owmi89](https://s.surveyplanet.com/q5owmi89)
