### ISSUE TITLE
Scaffold initial project for front-end

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#45]
**__Task Description__**
- [ ] Initial project boilerplate for front-end
- [ ] Setup prettier and hooks for pre-commit
- [ ] Setup eslint
- [ ] Setup jest
- [ ] Setup initial config for tailwindcss

**__Technical Considerations__**
- **Language**: Typescript
- **Framework**: NextJs / React
- **Auth**: JWT + google
- **State Management**: TBD
- **Styling framework**: TailwindCSS
- **UI Kit / Lib**: TBD
- **Testing**: Jest / react-testing-library

**__Additional Considerations__**
[Typescript Handbook](https://www.typescriptlang.org/docs/handbook/intro.html)
[NextJS Docs](https://nextjs.org/docs/getting-started)
[Jest Docs](https://jestjs.io/docs/getting-started)
[React Testing Library Docs](https://testing-library.com/docs/react-testing-library/intro/)
[TailwindCSS Docs](https://tailwindcss.com/docs)
