### ISSUE TITLE
CRUD for Authors

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#50]
**__Task Description__**
CRUD Operations for authors

**__Technical Considerations__**
- [ ] Create Author Schema/Entity
- [ ] Create Author Controller
- [ ] Create Author API Properties
- [ ] Validate DTOs

**__Additional Considerations__**
[https://app.zenhub.com/files/401346050/2ef2f170-434b-4e74-b242-f29bd91a828a/download](https://app.zenhub.com/files/401346050/2ef2f170-434b-4e74-b242-f29bd91a828a/download)
