### ISSUE TITLE
CRUD for Books

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#51]
**__Task Description__**
CRUD Operations for books

**__Technical Considerations__**
- [x] Create Book Schema/Entity
- [x] Create Book Controller
- [x] Create Book API Properties
- [x] Validate DTOs

**__Additional Considerations__**
[https://app.zenhub.com/files/401346050/2ef2f170-434b-4e74-b242-f29bd91a828a/download](https://app.zenhub.com/files/401346050/2ef2f170-434b-4e74-b242-f29bd91a828a/download)
