### ISSUE TITLE
CRUD for Category

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#73]
**__Task Description__**
CRUD Operations for category

**__Technical Considerations__**
- [x] Create Category Schema/Entity
- [x] Create Category Controller
- [x] Create Category API Properties
- [x] Validate DTOs

**__Additional Considerations__**
[https://app.zenhub.com/files/401346050/2ef2f170-434b-4e74-b242-f29bd91a828a/download](https://app.zenhub.com/files/401346050/2ef2f170-434b-4e74-b242-f29bd91a828a/download)
