### ISSUE TITLE
CRUD for Review

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#74]
**__Task Description__**
CRUD Operations for review

**__Technical Considerations__**
- [ ] Create Review Schema/Entity
- [ ] Create Review Controller
- [ ] Create Review API Properties
- [ ] Validate DTOs

**__Additional Considerations__**
[https://app.zenhub.com/files/401346050/2ef2f170-434b-4e74-b242-f29bd91a828a/download](https://app.zenhub.com/files/401346050/2ef2f170-434b-4e74-b242-f29bd91a828a/download)
